GO
USE PROYECTO_APO
GO

---------------------------------------------------------------AGREGAR------------------------------------------------------


------------------------------------CARGO-------------------------
CREATE PROCEDURE AGREGAR_CARGO
	@NOMBRE_CARGO VARCHAR (30),
	@ID_ESTADO_CARGO_FK INT
AS
	INSERT INTO CARGO (NOMBRE_CARGO,ID_ESTADO_CARGO_FK)
	VALUES (@NOMBRE_CARGO,@ID_ESTADO_CARGO_FK)


-----------------------------------	CLIENTES------------------
CREATE PROCEDURE AGREGAR_CLIENTE
	@IDENTIFICACION_CLIENTE INT,
	@NOMBRE_CLIENTE VARCHAR (30),
	@TELEFONO_CLIENTE BIGINT,
	@CORREO_CLIENTE VARCHAR (30),
	@ID_ESTADO_CLIENTE_FK INT
AS
	INSERT INTO CLIENTES (IDENTIFICACION_CLIENTE,NOMBRE_CLIENTE,TELEFONO_CLIENTE,CORREO_CLIENTE,ID_ESTADO_CLIENTE_FK)
	VALUES (@IDENTIFICACION_CLIENTE,@NOMBRE_CLIENTE,@TELEFONO_CLIENTE,@CORREO_CLIENTE,@ID_ESTADO_CLIENTE_FK)


---------------------------------------COMPRAS-------------------------------
CREATE PROCEDURE AGREGAR_COMPRA
	@NUMERO_FACTURA_PROVEEDOR INT,
	@SUBTOTAL_FACTURAC BIGINT,
	@FECHA_FACTURAC VARCHAR (30),
	@VALOR_FACTURA_C BIGINT,
	@IVA_FACTURA_C BIGINT,
	@ID_EMPLEADOFC INT,
	@CODIGO_PROVEEDOR_FC INT,
	@ID_ESTADO_FC INT,
	@ID_FORMA_PAGO_FK INT
AS
	INSERT INTO COMPRAS (NUMERO_FACTURA_PROVEEDOR, SUBTOTAL_FACTURAC , FECHA_FACTURAC,VALOR_FACTURA_C,IVA_FACTURA_C ,ID_EMPLEADOFC,CODIGO_PROVEDOR_FC,ID_ESTADO_FC,ID_FORMA_PAGO_FK)
	VALUES (@NUMERO_FACTURA_PROVEEDOR,@SUBTOTAL_FACTURAC,@FECHA_FACTURAC,@VALOR_FACTURA_C,@IVA_FACTURA_C,@ID_EMPLEADOFC,@CODIGO_PROVEEDOR_FC,@ID_ESTADO_FC,@ID_FORMA_PAGO_FK)

--------------------------------------CONTRATO--------------------------------
CREATE PROCEDURE AGREGAR_CONTRATO
	@NOMBRE_CONTRATO VARCHAR (30),
	@FECHA_INICIO_CONTRATO VARCHAR (30),
	@DURACION_CONTRATO VARCHAR (30),
	@FECHA_FIN_CONTRATO VARCHAR (30),
	@ID_ESTADO_C INT,
	@VALOR_CONTRATO BIGINT
AS
	INSERT INTO CONTRATO (NOMBRE_CONTRATO,FECHA_INICIO_CONTRATO,DURACION_CONTRATO,FECHA_FIN_CONTRATO,ID_ESTADO_C,VALOR_CONTRATO)
	VALUES (@NOMBRE_CONTRATO,@FECHA_INICIO_CONTRATO,@DURACION_CONTRATO,@FECHA_FIN_CONTRATO,@ID_ESTADO_C,@VALOR_CONTRATO)

-------------------------------------DEVOLUCION-----------------------------
CREATE PROCEDURE AGREGAR_DEVOLUCION
	@FECHA_DEVOLUCION VARCHAR (30),
	@ID_ESTADO_F_FK INT ,
	@ID_CLIENTE_D INT,
	@ID_EMPLEADO_D INT
AS
	INSERT INTO DEVOLUCION_PRODUCTO (FECHA_DEVOLUCION,ID_ESTADO_D_FK,ID_CLIENTE_D,ID_EMPLEADO_D)
	VALUES (@FECHA_DEVOLUCION,@ID_ESTADO_F_FK,@ID_CLIENTE_D,@ID_EMPLEADO_D)


-------------------------------------EMPLEADO---------------------------------
CREATE PROCEDURE AGREGAR_EMPLEADO
	@IDENTIFICACION_EMPLEADO INT,
	@NOMBRE_EMPLEADO VARCHAR (30),
	@TELEFONO_EMPLEADO BIGINT,
	@DIRECCION_EMPLEADO VARCHAR (30),
	@SALARIO_EMPLEADO BIGINT,
	@FECHA_NACIMIENTO_EMPLEADO VARCHAR (30),
	@CORREO_EMPLEADO VARCHAR (30),
	@FECHA_INGRESO_EMPLEADO VARCHAR (30),
	@ID_ESTADO_E INT,
	@NUMERO_CONTRATO_E INT,
	@CODIGO_CARGO_E INT
AS
	INSERT INTO EMPLEADO (IDENTIFICACION_EMPLEADO,NOMBRE_EMPLEADO,TELEFONO_EMPLEADO,DIRECCION_EMPLEADO,SALARIO_EMPLEADO,FECHA_NACIMIENTO_EMPLEADO,CORREO_EMPLEADO,FECHA_INGRESO_EMPLEADO,ID_ESTADO_E,NUMERO_CONTRATO_E,CODIGO_CARGO_E)
	VALUES (@IDENTIFICACION_EMPLEADO,@NOMBRE_EMPLEADO,@TELEFONO_EMPLEADO,@DIRECCION_EMPLEADO,@SALARIO_EMPLEADO,@FECHA_NACIMIENTO_EMPLEADO,@CORREO_EMPLEADO,@FECHA_INGRESO_EMPLEADO,@ID_ESTADO_E,@NUMERO_CONTRATO_E,@CODIGO_CARGO_E)



---------------------------------ESTADO------------------------------------------
CREATE PROCEDURE AGREGAR_ESTADO
	@NOMBRE_ESTADO VARCHAR (30)
AS
	INSERT INTO ESTADO (NOMBRE_ESTADO)
	VALUES (@NOMBRE_ESTADO)


--------------------------------FORMA PAGO---------------------------------------
CREATE PROCEDURE AGREGAR_FORMA_PAGO
	@NOMBRE_FORMA_PAGO VARCHAR (30),
	@ID_ESTADO_FP INT
AS
	INSERT INTO FORMA_PAGO (NOMBRE_FORMA_PAGO,ID_ESTADO_FP)
	VALUES (@NOMBRE_FORMA_PAGO,@ID_ESTADO_FP)


-------------------------------GARANTIA------------------------------------------
CREATE PROCEDURE AGREGAR_GARANTIA
	@TIEMPO_TOTAL VARCHAR (30),
	@FECHA_INICIO_GARANTIA VARCHAR (30),
	@FECHA_FIN_GARANTIA VARCHAR (30),
	@ID_ESTADO_GARANTIA INT

AS
	INSERT INTO GARANTIA (TIEMPO_TOTAL,FECHA_INICIO_GARANTIA,FECHA_FIN_GARANTIA,ID_ESTADO_GARANTIA)
	VALUES (@TIEMPO_TOTAL,@FECHA_INICIO_GARANTIA,@FECHA_FIN_GARANTIA,@ID_ESTADO_GARANTIA)

-------------------------------PRODUCTOS------------------------------------------
CREATE PROCEDURE AGREGAR_PRODUCTOS
	@CODIGO_PRODUCTO INT,
	@NOMBRE_PRODUCTO VARCHAR (30),
	@CANTIDAD_PRODUCTOS NUMERIC,
	@CANTIDAD_MINIMA_PRODUCTOS BIGINT,
	@CANTIDAD_MAXIMA_PRODUCTOS BIGINT,
	@VALOR_COMPRA_PRODUCTOS BIGINT,
	@VALOR_VENTA_PRODUCTOS BIGINT,
	@ID_ESTADO_PRODUCTO INT,
	@ID_GARANTIA_PRODUCTO INT,
	@CODIGO_PRESENTACION_PRODUCTO INT,
	@UNIDAD_MEDIDA_PRODUCTO VARCHAR (30)
AS
	INSERT INTO PRODUCTOS (CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CANTIDAD_PRODUCTOS,CANTIDAD_MINIMA_PRODUCTOS,CANTIDAD_MAXIMA_PRODUCTOS,VALOR_COMPRA_PRODUCTOS,VALOR_VENTA_PRODUCTOS,ID_ESTADO_PRODUCTO,ID_GARANTIA_PRODUCTO,CODIGO_PRESENTACION_PRODUCTO,UNIDAD_MEDIDA_PRODUCTO)
	VALUES (@CODIGO_PRODUCTO,@NOMBRE_PRODUCTO,@CANTIDAD_PRODUCTOS,@CANTIDAD_MINIMA_PRODUCTOS,@CANTIDAD_MAXIMA_PRODUCTOS,@VALOR_COMPRA_PRODUCTOS,@VALOR_VENTA_PRODUCTOS,@ID_ESTADO_PRODUCTO,@ID_GARANTIA_PRODUCTO,@CODIGO_PRESENTACION_PRODUCTO,@UNIDAD_MEDIDA_PRODUCTO)


-----------------------------PROVEEDORES--------------------------------------
CREATE PROCEDURE AGREGAR_PROVEEDOR
	@CODIGO_PROVEEDOR INT,
	@NOMBRE_PROVEEDOR VARCHAR (30),
	@R_SOCIAL_PROVEEDOR VARCHAR (30),
	@DIRECCION_PROVEEDOR VARCHAR (30),
	@CIUDAD_PROVEEDOR VARCHAR (30),
	@C_POSTAL_PROVEEDOR NUMERIC,
	@TELEFONO_PROVEEDOR BIGINT,
	@C_ELECTRONICO_PROVEEDOR VARCHAR (30),
	@ID_ESTADO_PROVEEDOR INT
AS
	INSERT INTO PROVEEDORES (CODIGO_PROVEEDOR,NOMBRE_PROVEEDOR,R_SOCIAL_PROVEEDOR,DIRECCION_PROVEEDOR,CIUDAD_PROVEEDOR,C_POSTAL_PROVEEDOR,TELEFONO_PROVEEDOR,C_ELECTRONICO_PROVEEDOR,ID_ESTADO_PROVEEDOR)
	VALUES (@CODIGO_PROVEEDOR,@NOMBRE_PROVEEDOR,@R_SOCIAL_PROVEEDOR,@DIRECCION_PROVEEDOR,@CIUDAD_PROVEEDOR,@C_POSTAL_PROVEEDOR,@TELEFONO_PROVEEDOR,@C_ELECTRONICO_PROVEEDOR,@ID_ESTADO_PROVEEDOR)



--------------------------------------TIPO PRESENTACION------------------
CREATE PROCEDURE AGREGAR_TIPO_PRESENTACION
	@NOMBRE_TPRESENTACION VARCHAR (30),
	@ID_ESTADO_TPRESENTACION INT
AS
	INSERT INTO TIPO_PRESENTACION (NOMBRE_TPRESENTACION,ID_ESTADO_TPRESENTACION)
	VALUES (@NOMBRE_TPRESENTACION,@ID_ESTADO_TPRESENTACION)

--------------------------------------USUARIO-----------------------------
CREATE PROCEDURE AGREGAR_USUARIO
	@NOMBRE_USUARIO VARCHAR (30),
	@CLAVE_USUARIO VARCHAR (30),
	@TIPO_USUARIO VARCHAR (30),
	@ID_ESTADO_U INT,
	@ID_EMPLEADO_U INT

AS
	INSERT INTO USUARIO (NOMBRE_USUARIO,CLAVE_USUARIO,TIPO_USUARIO,ID_ESTADO_U,ID_EMPLEADO_U)
	VALUES (@NOMBRE_USUARIO,@CLAVE_USUARIO,@TIPO_USUARIO,@ID_ESTADO_U,@ID_EMPLEADO_U)


------------------------------------VENTAS--------------------------------
CREATE PROCEDURE AGREGAR_VENTAS
	@FECHA_FACV VARCHAR (30),
	@SUBTOTAL_FACV BIGINT,
	@IVA_FACTURA_V BIGINT,
	@VALOR_FACTURAV BIGINT,
	@ID_CLIENTEFV INT,
	@ID_ESTADO_FV INT,
	@ID_EMPLEADOFV INT,
	@ID_FORMA_PAGO_FV INT
AS
	INSERT INTO VENTAS (FECHA_FACV,SUBTOTAL_FACV,IVA_FACTURA_V,VALOR_FACTURAV,ID_CLIENTEFV,ID_ESTADO_FV , ID_EMPLEADOFV,ID_FORMA_PAGO_FV)
	VALUES (@FECHA_FACV,@SUBTOTAL_FACV,@IVA_FACTURA_V,@VALOR_FACTURAV,@ID_CLIENTEFV,@ID_ESTADO_FV,@ID_EMPLEADOFV,@ID_FORMA_PAGO_FV)



--------------------------------------------------------------DETALLES--------------------------------------------------


-----------------------------------------DETALLE DEVOLUCION------------------------------------
CREATE PROCEDURE AGREGAR_DETALLE_DEVOLUCION
	@CODIGO_PRODUCTODTD INT,
	@VALOR_PRODUCTODTD BIGINT,
	@CANTIDAD_PRODUCTODTD NUMERIC,
	@CODIGO_DEVOLUCION_FK INT
AS 
	INSERT INTO DETALLE_DEVOLUCION (CODIGO_PRODUCTODTD,VALOR_PRODUCTODTD,CANTIDAD_PRODUCTODTD,CODIGO_DEVOLUCION_FK)
	VALUES (@CODIGO_PRODUCTODTD,@VALOR_PRODUCTODTD,@CANTIDAD_PRODUCTODTD,@CODIGO_DEVOLUCION_FK)




-----------------------------------------DETALLE COMPRAS---------------------------------------
CREATE PROCEDURE AGREGAR_DETALLE_FACTURA_COMPRA
	@CODIGO_PRODUCTO_FC INT,
	@VALOR_UNITARIO_FC BIGINT,
	@CANTIDAD_PRODUCTOSFC NUMERIC,
	@SUBTOTAL_FC BIGINT,
	@NUMERO_FACTURAC_FK INT
AS
	INSERT INTO DETALLE_FACTURA_COMPRA (CODIGO_PRODUCTO_FC,VALOR_UNITARIO_FC,CANTIDAD_PRODUCTOSFC,SUBTOTAL_FC,NUMERO_FACTURAC_FK)
	VALUES (@CODIGO_PRODUCTO_FC ,@VALOR_UNITARIO_FC,@CANTIDAD_PRODUCTOSFC,@SUBTOTAL_FC,@NUMERO_FACTURAC_FK)


------------------------------------DETALLE VENTAS---------------------------------------------
CREATE PROCEDURE AGREGAR_DETALLE_FACTURA_VENTA
	@CODIGO_PRODUCTODFV INT ,
	@NUMERO_FACTURAV VARCHAR (30),
	@CANTIDAD_PRODUCTOS_FACV NUMERIC,
	@VALOR_UNITARIOFV BIGINT,
	@SUBTOTALFV BIGINT
AS
	INSERT INTO DETALLE_FACTURA_VENTA (CODIGO_PRODUCTODFV,NUMERO_FACTURAV,CANTIDAD_PRODUCTOS_FACV,VALOR_UNITARIOFV,SUBTOTALFV)
	VALUES (@CODIGO_PRODUCTODFV,@NUMERO_FACTURAV,@CANTIDAD_PRODUCTOS_FACV,@VALOR_UNITARIOFV,@SUBTOTALFV)

