GO
USE PROYECTO_APO
GO

--------------------CARGO-------------------
CREATE PROCEDURE ELIMINAR_CARGO
	@CODIGO_CARGO INT
	AS
	DELETE CARGO WHERE CODIGO_CARGO = @CODIGO_CARGO
-------------------CLIENTES-----------------
CREATE PROCEDURE ELIMINAR_CLIENTES
	@IDENTIFICACION_CLIENTE INT
	AS
	DELETE CLIENTES WHERE IDENTIFICACION_CLIENTE = @IDENTIFICACION_CLIENTE 
-------------------COMPRAS-----------------
CREATE PROCEDURE ELIMINAR_COMPRA
	@NUMERO_FACTURAC INT
	AS
	DELETE COMPRAS WHERE NUMERO_FACTURAC = @NUMERO_FACTURAC
-------------------CONTRATO--------------
CREATE PROCEDURE ELIMINAR_CONTRATO
	@NUMERO_CONTRATO INT
	AS
	DELETE CONTRATO WHERE NUMERO_CONTRATO = @NUMERO_CONTRATO
-------------------EMPLEADO-------------
CREATE PROCEDURE ELIMINAR_EMPLEADO
	@IDENTIFICACION_EMPLEADO INT
	AS
	DELETE EMPLEADO WHERE IDENTIFICACION_EMPLEADO = @IDENTIFICACION_EMPLEADO
--------------------ESTADO------------
CREATE PROCEDURE ELIMINAR_ESTADO
	@ID_ESTADO INT
	AS
	DELETE ESTADO WHERE ID_ESTADO = @ID_ESTADO
--------------------FORMA_PAGO-------
CREATE PROCEDURE ELIMINAR_FORMA_PAGO
	@ID_FORMA_PAGO INT
	AS
	DELETE FORMA_PAGO WHERE ID_FORMA_PAGO = @ID_FORMA_PAGO
-------------------GARANTIA--------
CREATE PROCEDURE ELIMINAR_GARANTIA
	@ID_GARANTIA INT
	AS
	DELETE GARANTIA WHERE ID_GARANTIA = @ID_GARANTIA
-------------------PRODUCTOS-------
CREATE PROCEDURE ELIMINAR_PRODUCTOS
	@CODIGO_PRODUCTO INT 
	AS
	DELETE PRODUCTOS WHERE CODIGO_PRODUCTO = @CODIGO_PRODUCTO
-------------------PROVEEDORES----
CREATE PROCEDURE ELIMINAR_PROVEEDORES
	@CODIGO_PROVEEDOR INT
	AS
	DELETE PROVEEDORES WHERE CODIGO_PROVEEDOR = @CODIGO_PROVEEDOR


-------------------TIPO PRESENTACION---
CREATE PROCEDURE ELIMINAR_TIPO_PRESENTACION
	@CODIGO_TPRESENTACION INT
	AS
	DELETE TIPO_PRESENTACION WHERE CODIGO_TPRESENTACION = @CODIGO_TPRESENTACION
--------------------USUARIO-----------
CREATE PROCEDURE ELIMINAR_USUARIO
	@ID_USUARIO INT
	AS
	DELETE USUARIO WHERE ID_USUARIO = @ID_USUARIO
-------------------VENTAS------------
CREATE PROCEDURE ELIMINAR_VENTAS
	@NUMERO_FACTURA_V INT
	AS
	DELETE VENTAS WHERE NUMERO_FACTURA_V = @NUMERO_FACTURA_V




-----------------------------------...........DETALLES...............----------------------------


-----------DETALLE DEVOLUCION-----------
CREATE PROCEDURE ELIMINAR_DETALLE_DEVOLUCION
	@ID_DETALLEDV INT
	AS
	DELETE DETALLE_DEVOLUCION WHERE ID_DETALLEDV = @ID_DETALLEDV

-----------DETALLE COMPRA------------
CREATE PROCEDURE ELIMINAR_DETALLE_COMPRA
	@ID_DETALLE_FACTURA_C INT
	AS
	DELETE DETALLE_FACTURA_COMPRA WHERE ID_DETALLE_FACTURA_C = @ID_DETALLE_FACTURA_C
-----------DETALLE VENTA-----------
CREATE PROCEDURE ELIMINAR_DETALLE_VENTA
	@ID_DETALLEFACTURAV INT
	AS
	DELETE DETALLE_FACTURA_VENTA WHERE ID_DETALLEFACTURAV = @ID_DETALLEFACTURAV
