GO
USE PROYECTO_APO
GO


-------------CARGO---------
CREATE PROCEDURE CONSULTAR_CARGOS
AS
SELECT CARGO.CODIGO_CARGO AS[Codigo] , CARGO.NOMBRE_CARGO AS [Nombre] , ESTADO.NOMBRE_ESTADO AS [Estado] FROM CARGO INNER JOIN ESTADO ON ID_ESTADO =ID_ESTADO_CARGO_FK
-------------CLIENTES-----
CREATE PROCEDURE CONSULTAR_CLIENTES
AS
SELECT CLIENTES.IDENTIFICACION_CLIENTE AS[Identificación], CLIENTES.NOMBRE_CLIENTE AS[Nombre], CLIENTES.TELEFONO_CLIENTE AS[Telefono] , CLIENTES.CORREO_CLIENTE AS[Correo Electronico], ESTADO.NOMBRE_ESTADO AS[Estado] FROM CLIENTES INNER JOIN ESTADO ON ID_ESTADO = ID_ESTADO_CLIENTE_FK
-------------CONTRATO-----
CREATE PROCEDURE CONSULTAR_CONTRATOS
AS
SELECT CONTRATO.NUMERO_CONTRATO AS[Numero Contrato], CONTRATO.NOMBRE_CONTRATO AS[Nombre] ,CONTRATO.FECHA_INICIO_CONTRATO AS[Inicio], CONTRATO.DURACION_CONTRATO AS[Duración],CONTRATO.FECHA_FIN_CONTRATO AS [Fin], ESTADO.NOMBRE_ESTADO AS[Estado]  , CONTRATO.VALOR_CONTRATO AS[Valor] FROM CONTRATO INNER JOIN  ESTADO ON  ID_ESTADO = ID_ESTADO_C

-------------DEVOLUCION
CREATE PROCEDURE CONSULTAR_DEVOLUCION 
AS
SELECT DEVOLUCION_PRODUCTO.CODIGO_DEVOLUCION AS [Devolucion No], DEVOLUCION_PRODUCTO.FECHA_DEVOLUCION AS [Fecha], ESTADO.NOMBRE_ESTADO AS [Estado] , CLIENTES.NOMBRE_CLIENTE AS [Cliente], EMPLEADO.NOMBRE_EMPLEADO AS [Empleado]
FROM DEVOLUCION_PRODUCTO
 INNER JOIN ESTADO ON ID_ESTADO = ID_ESTADO_D_FK INNER JOIN CLIENTES ON IDENTIFICACION_CLIENTE = ID_CLIENTE_D
 INNER JOIN EMPLEADO ON IDENTIFICACION_EMPLEADO = DEVOLUCION_PRODUCTO.ID_EMPLEADO_D
-------------EMPLEADOS----------
CREATE PROCEDURE CONSULTAR_EMPLEADOS
AS
SELECT EMPLEADO.IDENTIFICACION_EMPLEADO AS[Identificación], EMPLEADO.NOMBRE_EMPLEADO  AS[Nombre], EMPLEADO.TELEFONO_EMPLEADO AS[Telefono] , EMPLEADO.DIRECCION_EMPLEADO AS[Dirección] , EMPLEADO.SALARIO_EMPLEADO AS[Salario] , EMPLEADO.FECHA_NACIMIENTO_EMPLEADO AS[Fecha Nacimiento], EMPLEADO.CORREO_EMPLEADO AS[Correo] ,EMPLEADO.FECHA_INGRESO_EMPLEADO AS[Fecha Ingreso], ESTADO.NOMBRE_ESTADO AS[Estado], CONTRATO.NOMBRE_CONTRATO AS[Contrato] , CARGO.NOMBRE_CARGO AS[Cargo] FROM EMPLEADO INNER JOIN ESTADO ON ID_ESTADO = ID_ESTADO_E INNER JOIN CONTRATO ON NUMERO_CONTRATO = NUMERO_CONTRATO_E INNER JOIN CARGO ON CODIGO_CARGO = CODIGO_CARGO_E

--------------ESTADO----------
CREATE PROCEDURE CONSULTAR_ESTADOS
AS
SELECT ESTADO.ID_ESTADO AS [Id],ESTADO.NOMBRE_ESTADO AS[Nombre] FROM ESTADO
-------------FORMA_PAGO--------
CREATE PROCEDURE CONSULTAR_FORMAS_PAGO
AS
SELECT FORMA_PAGO.ID_FORMA_PAGO AS [Codigo], FORMA_PAGO.NOMBRE_FORMA_PAGO AS [Nombre], ESTADO.NOMBRE_ESTADO  AS [Estado] FROM FORMA_PAGO INNER JOIN ESTADO ON ID_ESTADO = FORMA_PAGO.ID_ESTADO_FP;
-------------GARANTIA---------
CREATE PROCEDURE CONSULTAR_GARANTIAS
AS
SELECT GARANTIA.ID_GARANTIA AS [Id], GARANTIA.TIEMPO_TOTAL AS[Tiempo Total] , GARANTIA.FECHA_INICIO_GARANTIA AS[Fecha Inicio] , GARANTIA.FECHA_FIN_GARANTIA AS[Fecha Fin], ESTADO.NOMBRE_ESTADO AS [Estado] FROM GARANTIA INNER JOIN ESTADO ON ID_ESTADO = GARANTIA.ID_ESTADO_GARANTIA;

-------------INVENTARIO----
CREATE PROCEDURE CONSULTAR_INVENTARIOS
AS
SELECT INVENTARIO.NUMERO_INVENTARIO AS [Numero] , INVENTARIO.FECHA_INVENTARIO AS [Fecha] ,INVENTARIO.TIPO_MOVIMIENTO AS [Movimiento] ,EMPLEADO.NOMBRE_EMPLEADO AS [Empleado],ESTADO.NOMBRE_ESTADO AS [Estado]  FROM  INVENTARIO INNER JOIN EMPLEADO ON IDENTIFICACION_EMPLEADO = INVENTARIO.EMPLEADO_INVENTARIO INNER JOIN  ESTADO ON  ESTADO.ID_ESTADO = INVENTARIO.ID_ESTADO_INVENTARIO


------------PRODUCTOS----
CREATE PROCEDURE CONSULTAR_PRODUCTOS
AS
SELECT PRODUCTOS.CODIGO_PRODUCTO AS [Codigo], PRODUCTOS.NOMBRE_PRODUCTO AS[Nombre],PRODUCTOS.CANTIDAD_PRODUCTOS AS [Cantidad] , PRODUCTOS.CANTIDAD_MINIMA_PRODUCTOS AS [Cantidad Minima] , PRODUCTOS.CANTIDAD_MAXIMA_PRODUCTOS AS [Cantidad Máxima],PRODUCTOS.VALOR_COMPRA_PRODUCTOS AS [Valor Compra],PRODUCTOS.VALOR_VENTA_PRODUCTOS AS [Valor Venta] , ESTADO.NOMBRE_ESTADO AS [Estado], GARANTIA.TIEMPO_TOTAL AS [Garantía],TIPO_PRESENTACION.NOMBRE_TPRESENTACION AS [Presentación], PRODUCTOS.UNIDAD_MEDIDA_PRODUCTO AS [Unidad Medida] 
FROM PRODUCTOS INNER JOIN ESTADO ON ID_ESTADO = ID_ESTADO_PRODUCTO INNER JOIN GARANTIA ON ID_GARANTIA = ID_GARANTIA_PRODUCTO INNER JOIN TIPO_PRESENTACION ON CODIGO_TPRESENTACION = CODIGO_PRESENTACION_PRODUCTO

------------PROVEEDORES-----
CREATE PROCEDURE CONSULTAR_PROVEEDORES
AS
SELECT PROVEEDORES.CODIGO_PROVEEDOR AS [Codigo], PROVEEDORES.NOMBRE_PROVEEDOR [Nombre],PROVEEDORES.R_SOCIAL_PROVEEDOR AS [Razón Social],PROVEEDORES.DIRECCION_PROVEEDOR AS [Dirección], PROVEEDORES.CIUDAD_PROVEEDOR AS [Ciudad], PROVEEDORES.C_POSTAL_PROVEEDOR AS [Codigo Postal] , PROVEEDORES.TELEFONO_PROVEEDOR AS [Telefono],PROVEEDORES.C_ELECTRONICO_PROVEEDOR AS[Correo Electronico] , ESTADO.NOMBRE_ESTADO AS [Estado] FROM PROVEEDORES INNER JOIN ESTADO ON  ID_ESTADO = ID_ESTADO_PROVEEDOR

------------TIPO_PRESENTACION------
CREATE PROCEDURE CONSULTAR_PRESENTACIONES
AS
SELECT TIPO_PRESENTACION.CODIGO_TPRESENTACION AS [Codigo],TIPO_PRESENTACION.NOMBRE_TPRESENTACION AS [Nombre], ESTADO.NOMBRE_ESTADO AS [Estado] FROM TIPO_PRESENTACION INNER JOIN ESTADO ON ID_ESTADO = ID_ESTADO_TPRESENTACION

-----------USUARIO------------
CREATE PROCEDURE CONSULTAR_USUARIOS
AS
SELECT ID_USUARIO AS [Id] , NOMBRE_USUARIO AS [Nombre] , CLAVE_USUARIO AS[Clave],TIPO_USUARIO AS [Tipo], ESTADO.NOMBRE_ESTADO AS [Estado], EMPLEADO.NOMBRE_EMPLEADO AS [Nombre Empleado]  FROM USUARIO INNER JOIN ESTADO  ON ID_ESTADO = ID_ESTADO_U INNER JOIN EMPLEADO ON IDENTIFICACION_EMPLEADO = ID_EMPLEADO_U


---------VENTAS--------------
CREATE PROCEDURE CONSULTAR_VENTAS
AS
SELECT VENTAS.NUMERO_FACTURA_V AS [No], VENTAS.FECHA_FACV AS [Fecha] ,ESTADO.NOMBRE_ESTADO AS [Estado],  EMPLEADO.NOMBRE_EMPLEADO AS [Empleado]  ,CLIENTES.NOMBRE_CLIENTE AS [Cliente], FORMA_PAGO.NOMBRE_FORMA_PAGO AS [Forma Pago], VENTAS.SUBTOTAL_FACV AS [Subtotal], VENTAS.IVA_FACTURA_V AS [Iva] , VENTAS.VALOR_FACTURAV AS [Valor Factura] 
FROM VENTAS INNER JOIN ESTADO ON ESTADO.ID_ESTADO = VENTAS.ID_ESTADO_FV INNER JOIN EMPLEADO ON EMPLEADO.IDENTIFICACION_EMPLEADO = VENTAS.ID_EMPLEADOFV INNER JOIN CLIENTES ON CLIENTES.IDENTIFICACION_CLIENTE = VENTAS.ID_CLIENTEFV INNER JOIN FORMA_PAGO ON FORMA_PAGO.ID_FORMA_PAGO = VENTAS.ID_FORMA_PAGO_FV

--------COMPRAS
CREATE PROCEDURE CONSULTAR_COMPRAS
AS
SELECT COMPRAS.NUMERO_FACTURAC AS [No], COMPRAS.NUMERO_FACTURA_PROVEEDOR AS [No Proveedor] , COMPRAS.FECHA_FACTURAC AS [Fecha] , PROVEEDORES.NOMBRE_PROVEEDOR AS [Proveedor], EMPLEADO.NOMBRE_EMPLEADO AS [Empleado] , FORMA_PAGO.NOMBRE_FORMA_PAGO AS [Forma Pago], ESTADO.NOMBRE_ESTADO AS [Estado] , COMPRAS.SUBTOTAL_FACTURAC AS [Subtotal], COMPRAS.IVA_FACTURA_C AS [Iva],COMPRAS.VALOR_FACTURA_C AS [Valor Factura]
FROM COMPRAS INNER JOIN PROVEEDORES ON PROVEEDORES.CODIGO_PROVEEDOR = COMPRAS.CODIGO_PROVEDOR_FC INNER JOIN EMPLEADO ON EMPLEADO.IDENTIFICACION_EMPLEADO = COMPRAS.ID_EMPLEADOFC INNER JOIN FORMA_PAGO ON FORMA_PAGO.ID_FORMA_PAGO = COMPRAS.ID_FORMA_PAGO_FK INNER JOIN ESTADO ON ESTADO.ID_ESTADO = COMPRAS.ID_ESTADO_FC

-------------DETALLE VENTA------------
CREATE PROCEDURE CONSULTAR_DETALLE_VENTA
@NUMERO_FACTURA_V INT 
AS
SELECT DISTINCT DETALLE_FACTURA_VENTA.ID_DETALLEFACTURAV AS [Detalle No], PRODUCTOS.NOMBRE_PRODUCTO AS [Producto] , DETALLE_FACTURA_VENTA.VALOR_UNITARIOFV [Valor Unitario] ,DETALLE_FACTURA_VENTA.CANTIDAD_PRODUCTOS_FACV AS [Cantidad] ,  DETALLE_FACTURA_VENTA.SUBTOTALFV AS [Subtotal] 
FROM VENTAS,DETALLE_FACTURA_VENTA
INNER JOIN PRODUCTOS ON CODIGO_PRODUCTO = DETALLE_FACTURA_VENTA.CODIGO_PRODUCTODFV
WHERE DETALLE_FACTURA_VENTA.NUMERO_FACTURAV = @NUMERO_FACTURA_V


------------DETALLE_COMPRA--------
CREATE PROCEDURE CONSULTAR_DETALLE_COMPRA
@NUMERO_FACTURA_C INT
AS
SELECT DISTINCT DETALLE_FACTURA_COMPRA.ID_DETALLE_FACTURA_C AS [Detalle No] , PRODUCTOS.NOMBRE_PRODUCTO AS [Producto] , DETALLE_FACTURA_COMPRA.VALOR_UNITARIO_FC AS [Valor Unitario], DETALLE_FACTURA_COMPRA.CANTIDAD_PRODUCTOSFC AS [Cantidad], DETALLE_FACTURA_COMPRA.SUBTOTAL_FC AS [Subtotal]
FROM COMPRAS,DETALLE_FACTURA_COMPRA 
INNER JOIN PRODUCTOS ON PRODUCTOS.CODIGO_PRODUCTO = DETALLE_FACTURA_COMPRA.CODIGO_PRODUCTO_FC
WHERE DETALLE_FACTURA_COMPRA.NUMERO_FACTURAC_FK = @NUMERO_FACTURA_C

--DETALLE DEVOLUCION--
CREATE PROCEDURE CONSULTAR_DETALLE_DEVOLUCION
@NUMERO_DEVOLUCION INT
AS
SELECT DETALLE_DEVOLUCION.ID_DETALLEDV AS [Detalle No] , PRODUCTOS.NOMBRE_PRODUCTO AS [Producto], DETALLE_DEVOLUCION.VALOR_PRODUCTODTD AS [Valor] , DETALLE_DEVOLUCION.CANTIDAD_PRODUCTODTD AS [Cantidad] from DETALLE_DEVOLUCION INNER JOIN PRODUCTOS ON   PRODUCTOS.CODIGO_PRODUCTO = DETALLE_DEVOLUCION.CODIGO_PRODUCTODTD
WHERE DETALLE_DEVOLUCION.CODIGO_DEVOLUCION_FK = @NUMERO_DEVOLUCION




