GO 
USE PROYECTO_APO 
GO 

CREATE PROCEDURE LOGEO 
@NOMBRE_LOGEO VARCHAR (30),
@CLAVE_LOGEO VARCHAR (30),
@TIPO_USUARIO VARCHAR (30)
AS
SELECT USUARIO.NOMBRE_USUARIO , USUARIO.CLAVE_USUARIO , USUARIO.TIPO_USUARIO
FROM USUARIO
WHERE USUARIO.NOMBRE_USUARIO = @NOMBRE_LOGEO AND USUARIO.CLAVE_USUARIO = @CLAVE_LOGEO AND USUARIO.TIPO_USUARIO = @TIPO_USUARIO




