GO
USE PROYECTO_APO
GO



----------------------------------REPORTE EMPLEADOS---------------------------
CREATE VIEW RPT_GENERAL_EMPLEADOS
AS
SELECT EMPLEADO.IDENTIFICACION_EMPLEADO AS [Identificación] , EMPLEADO.NOMBRE_EMPLEADO AS [Nombre] ,
EMPLEADO.CORREO_EMPLEADO AS [Correo], CARGO.NOMBRE_CARGO AS [Cargo] ,
CONTRATO.DURACION_CONTRATO AS [Contrato] ,  EMPLEADO.SALARIO_EMPLEADO AS [Salario],
EMPLEADO.FECHA_INGRESO_EMPLEADO AS [Fecha Ingreso],ESTADO.NOMBRE_ESTADO AS [Estado]
FROM  EMPLEADO 
INNER JOIN CARGO  ON CODIGO_CARGO = EMPLEADO.CODIGO_CARGO_E 
INNER JOIN CONTRATO ON NUMERO_CONTRATO = EMPLEADO.NUMERO_CONTRATO_E 
INNER JOIN ESTADO  ON ID_ESTADO = EMPLEADO.ID_ESTADO_E

--ESPECIFICO--
CREATE PROCEDURE RPT_ESPECIFICO_EMPLEADOS
@IDENTIFICACION_EMPLEADO INT ,
@NOMBRE_EMPLEADO VARCHAR (30),
@CARGO_EMPLEADO VARCHAR (30),
@CONTRATO_EMPLEADO VARCHAR (30),
@ESTADO_EMPLEADO VARCHAR (30)
AS
SELECT EMPLEADO.IDENTIFICACION_EMPLEADO AS [Identificación] , EMPLEADO.NOMBRE_EMPLEADO AS [Nombre] ,
EMPLEADO.CORREO_EMPLEADO AS [Correo], CARGO.NOMBRE_CARGO AS [Cargo]  ,
CONTRATO.DURACION_CONTRATO AS [Contrato] , EMPLEADO.SALARIO_EMPLEADO AS [Salario],
EMPLEADO.FECHA_INGRESO_EMPLEADO AS [Fecha Ingreso], ESTADO.NOMBRE_ESTADO AS [Estado]
FROM  EMPLEADO
INNER JOIN CARGO  ON CODIGO_CARGO = EMPLEADO.CODIGO_CARGO_E 
INNER JOIN CONTRATO  ON NUMERO_CONTRATO = EMPLEADO.NUMERO_CONTRATO_E 
INNER JOIN ESTADO  ON ID_ESTADO = EMPLEADO.ID_ESTADO_E
WHERE IDENTIFICACION_EMPLEADO LIKE @IDENTIFICACION_EMPLEADO OR NOMBRE_EMPLEADO LIKE @NOMBRE_EMPLEADO OR CARGO.NOMBRE_CARGO LIKE @CARGO_EMPLEADO
OR CONTRATO.NOMBRE_CONTRATO LIKE @CONTRATO_EMPLEADO OR ESTADO.NOMBRE_ESTADO LIKE @ESTADO_EMPLEADO




---------------------------------REPORTE CLIENTES-------------------------
CREATE VIEW RPT_GENERAL_CLIENTE
AS 
SELECT CLIENTES.IDENTIFICACION_CLIENTE As [Identificación] , CLIENTES.NOMBRE_CLIENTE AS [Nombre] , CLIENTES.TELEFONO_CLIENTE AS [Telefono] ,CLIENTES.CORREO_CLIENTE AS [Correo] , ESTADO.NOMBRE_ESTADO AS [Estado] 
FROM CLIENTES
INNER JOIN ESTADO ON ESTADO.ID_ESTADO = CLIENTES.ID_ESTADO_CLIENTE_FK

---ESPECIFICO---
CREATE PROCEDURE RPT_ESPECIFICO_CLIENTE
@IDENTIFICACION_CLIENTE INT,
@NOMBRE_CLIENTE VARCHAR (30),
@ESTADO_CLIENTE VARCHAR (30)
AS
SELECT CLIENTES.IDENTIFICACION_CLIENTE As [Identificación] , CLIENTES.NOMBRE_CLIENTE AS [Nombre] , CLIENTES.TELEFONO_CLIENTE AS [Telefono] ,CLIENTES.CORREO_CLIENTE AS [Correo] , ESTADO.NOMBRE_ESTADO AS [Estado] 
FROM CLIENTES
INNER JOIN ESTADO ON ESTADO.ID_ESTADO = CLIENTES.ID_ESTADO_CLIENTE_FK
WHERE CLIENTES.IDENTIFICACION_CLIENTE LIKE @IDENTIFICACION_CLIENTE OR CLIENTES.NOMBRE_CLIENTE LIKE @NOMBRE_CLIENTE OR CLIENTES.ID_ESTADO_CLIENTE_FK LIKE @ESTADO_CLIENTE


--REPORTE PRODUCTOS--

CREATE PROCEDURE REPORTE_PRODUCTOS
AS
SELECT PRODUCTOS.CODIGO_PRODUCTO AS [Codigo], PRODUCTOS.NOMBRE_PRODUCTO AS [Nombre],
PRODUCTOS.VALOR_VENTA_PRODUCTOS AS [Valor],  PRODUCTOS.CANTIDAD_PRODUCTOS AS [Cantidad], 
PRODUCTOS.CANTIDAD_MINIMA_PRODUCTOS AS [Minima] , PRODUCTOS.CANTIDAD_MAXIMA_PRODUCTOS AS [Máxima],
GARANTIA.TIEMPO_TOTAL AS [Garantía], TIPO_PRESENTACION.NOMBRE_TPRESENTACION AS[Presentación]
FROM PRODUCTOS 
INNER JOIN GARANTIA ON ID_GARANTIA = ID_GARANTIA_PRODUCTO
INNER JOIN TIPO_PRESENTACION  ON CODIGO_TPRESENTACION = PRODUCTOS.CODIGO_PRESENTACION_PRODUCTO 


--------------------FACTURAS-------------

CREATE PROCEDURE RPT_COMPRA
@NUMERO_FAC INT
AS
SELECT COMPRAS.NUMERO_FACTURAC ,  COMPRAS.FECHA_FACTURAC,COMPRAS.SUBTOTAL_FACTURAC ,
COMPRAS.IVA_FACTURA_C ,COMPRAS.VALOR_FACTURA_C , EMPLEADO.NOMBRE_EMPLEADO,PROVEEDORES.NOMBRE_PROVEEDOR,
 FORMA_PAGO.NOMBRE_FORMA_PAGO , DETALLE_FACTURA_COMPRA.CODIGO_PRODUCTO_FC , DETALLE_FACTURA_COMPRA.VALOR_UNITARIO_FC , 
 DETALLE_FACTURA_COMPRA.CANTIDAD_PRODUCTOSFC , DETALLE_FACTURA_COMPRA.SUBTOTAL_FC 
FROM  DETALLE_FACTURA_COMPRA , COMPRAS 
INNER JOIN EMPLEADO ON IDENTIFICACION_EMPLEADO = ID_EMPLEADOFC
INNER JOIN PROVEEDORES ON CODIGO_PROVEEDOR = CODIGO_PROVEDOR_FC 
INNER JOIN FORMA_PAGO ON ID_FORMA_PAGO = ID_FORMA_PAGO_FK
WHERE NUMERO_FACTURAC = @NUMERO_FAC AND NUMERO_FACTURAC = DETALLE_FACTURA_COMPRA.NUMERO_FACTURAC_FK



CREATE PROCEDURE RPT_VENTA
@NUMERO_FAC INT
AS
SELECT VENTAS.NUMERO_FACTURA_V, VENTAS.FECHA_FACV , 
VENTAS.SUBTOTAL_FACV, VENTAS.IVA_FACTURA_V ,
VENTAS.VALOR_FACTURAV , EMPLEADO.NOMBRE_EMPLEADO,
CLIENTES.NOMBRE_CLIENTE, FORMA_PAGO.NOMBRE_FORMA_PAGO , 
DETALLE_FACTURA_VENTA.CODIGO_PRODUCTODFV,
DETALLE_FACTURA_VENTA.CANTIDAD_PRODUCTOS_FACV,
DETALLE_FACTURA_VENTA.VALOR_UNITARIOFV, DETALLE_FACTURA_VENTA.SUBTOTALFV
FROM    DETALLE_FACTURA_VENTA , VENTAS
INNER JOIN CLIENTES ON IDENTIFICACION_CLIENTE = VENTAS.ID_CLIENTEFV 
INNER JOIN EMPLEADO ON IDENTIFICACION_EMPLEADO = VENTAS.ID_EMPLEADOFV 
INNER JOIN FORMA_PAGO ON ID_FORMA_PAGO = ID_FORMA_PAGO_FV 
WHERE VENTAS.NUMERO_FACTURA_V = @NUMERO_FAC   AND NUMERO_FACTURA_V = DETALLE_FACTURA_VENTA.NUMERO_FACTURAV

---producto detalle venta---
CREATE PROCEDURE RPT_PRODVENTA
@NUMERO_FAC INT 
AS
SELECT
PRODUCTOS.NOMBRE_PRODUCTO
FROM DETALLE_FACTURA_VENTA
INNER JOIN PRODUCTOS ON CODIGO_PRODUCTODFV = DETALLE_FACTURA_VENTA.CODIGO_PRODUCTODFV
WHERE @NUMERO_FAC = DETALLE_FACTURA_VENTA.NUMERO_FACTURAV


-----------DEVOLUCION---------

CREATE PROCEDURE RPT_DEVOLCUCION
@CODIGO_DEVOLUCION INT
AS
SELECT DEVOLUCION_PRODUCTO.CODIGO_DEVOLUCION , ESTADO.NOMBRE_ESTADO ,CLIENTES.NOMBRE_CLIENTE,EMPLEADO.NOMBRE_EMPLEADO, 
DETALLE_DEVOLUCION.VALOR_PRODUCTODTD, DETALLE_DEVOLUCION.CANTIDAD_PRODUCTODTD 
FROM DETALLE_DEVOLUCION , DEVOLUCION_PRODUCTO
INNER JOIN ESTADO ON ID_ESTADO = DEVOLUCION_PRODUCTO.ID_ESTADO_D_FK
INNER JOIN CLIENTES ON IDENTIFICACION_CLIENTE = DEVOLUCION_PRODUCTO.ID_CLIENTE_D
INNER JOIN EMPLEADO ON IDENTIFICACION_EMPLEADO = DEVOLUCION_PRODUCTO.ID_EMPLEADO_D
WHERE DEVOLUCION_PRODUCTO.CODIGO_DEVOLUCION = @CODIGO_DEVOLUCION  AND DEVOLUCION_PRODUCTO.CODIGO_DEVOLUCION = DETALLE_DEVOLUCION.CODIGO_DEVOLUCION_FK


CREATE PROCEDURE RPT_PRODUCTODV 
@CODIGO_DEVOLUCION INT
AS
SELECT PRODUCTOS.NOMBRE_PRODUCTO
FROM DETALLE_DEVOLUCION
INNER JOIN PRODUCTOS ON CODIGO_PRODUCTO = DETALLE_DEVOLUCION.CODIGO_PRODUCTODTD
WHERE @CODIGO_DEVOLUCION = DETALLE_DEVOLUCION.CODIGO_DEVOLUCION_FK