GO
USE PROYECTO_APO
GO

SELECT *FROM CARGO
SELECT *FROM CLIENTES
SELECT *FROM COMPRAS
SELECT *FROM CONTRATO
SELECT *FROM DEVOLUCION_PRODUCTO
SELECT *FROM EMPLEADO
SELECT *FROM ESTADO
SELECT *FROM FORMA_PAGO
SELECT *FROM GARANTIA
SELECT *FROM INVENTARIO
SELECT *FROM PRODUCTOS
SELECT *FROM PROVEEDORES
SELECT *FROM TIPO_PRESENTACION
SELECT *FROM USUARIO
SELECT *FROM VENTAS
SELECT *FROM DETALLE_DEVOLUCION                                     
SELECT *FROM DETALLE_FACTURA_COMPRA
SELECT *FROM DETALLE_FACTURA_VENTA
SELECT *FROM DETALLE_INVENTARIO

