GO
USE PROYECTO_APO
GO

-------------------AUMENTO_COMPRAS----------------------

	CREATE TRIGGER EJECUTAR_COMPRA
	ON DETALLE_FACTURA_COMPRA FOR INSERT AS
	BEGIN 
		DECLARE @PRODUCTO AS INT
		DECLARE @CANTIDAD AS BIGINT
		DECLARE @CANTIDAD_MAXIMA AS BIGINT 
		
		SET @PRODUCTO  = (SELECT CODIGO_PRODUCTO_FC FROM INSERTED)
		SET @CANTIDAD  = (SELECT CANTIDAD_PRODUCTOSFC FROM INSERTED)
		SET @CANTIDAD_MAXIMA = (SELECT PRODUCTOS.CANTIDAD_MAXIMA_PRODUCTOS FROM PRODUCTOS WHERE PRODUCTOS.CODIGO_PRODUCTO = @PRODUCTO)

		IF @CANTIDAD > @CANTIDAD_MAXIMA
		BEGIN
			PRINT 'No se puede sobrepasar la bodega'
			rollback transaction 
		END

		ELSE

			BEGIN 
			UPDATE PRODUCTOS 
			SET CANTIDAD_PRODUCTOS = CANTIDAD_PRODUCTOS +@CANTIDAD
			WHERE CODIGO_PRODUCTO LIKE @PRODUCTO
		    END
	END

	----------------------CONTROL CONTABILIDAD-------------------

	
			
		CREATE TRIGGER MINIMO_VENTA
		ON DETALLE_FACTURA_VENTA FOR INSERT 
		AS
		BEGIN
			DECLARE @COD_PROD INT 
			DECLARE @CANT_VENTA INT
			DECLARE @CANTIDAD_PRODUCTOS INT

			SET @COD_PROD = (SELECT CODIGO_PRODUCTODFV FROM inserted)
			SET @CANTIDAD_PRODUCTOS = (SELECT CANTIDAD_PRODUCTOS FROM PRODUCTOS WHERE CODIGO_PRODUCTO = @COD_PROD)
			SET @CANT_VENTA = (SELECT CANTIDAD_PRODUCTOS_FACV FROM inserted)
				
			IF  @CANTIDAD_PRODUCTOS < @CANT_VENTA 
			BEGIN
				PRINT 'No hay suficientes productos'
				ROLLBACK TRANSACTION
			END
			ELSE
			BEGIN
			UPDATE PRODUCTOS
			SET CANTIDAD_PRODUCTOS = CANTIDAD_PRODUCTOS-@CANT_VENTA
			WHERE CODIGO_PRODUCTO LIKE @COD_PROD
			END
		END


-------------HISTORIAL COMPRA----------------
	CREATE TRIGGER HISTORIAL_COMPRA
	ON COMPRAS FOR INSERT
	AS
	BEGIN

		DECLARE @EMPLEADO_INVENTARIO INT
		DECLARE @ESTADO_INVENTARIO INT
		DECLARE @FECHA_INVENTARIO VARCHAR (30)
	
		SET @EMPLEADO_INVENTARIO = (SELECT ID_EMPLEADOFC FROM inserted)
		SET @ESTADO_INVENTARIO = (SELECT ID_ESTADO_FC FROM inserted)
		SET @FECHA_INVENTARIO = (SELECT FECHA_FACTURAC FROM inserted)
	
		INSERT INTO INVENTARIO 
		VALUES (@FECHA_INVENTARIO,'Entrada',@EMPLEADO_INVENTARIO,@ESTADO_INVENTARIO)
	END

---------------------HISTORIAL VENTA--------------------

	CREATE TRIGGER HISTORIAL_VENTA
	ON VENTAS FOR INSERT
	AS
	BEGIN

		DECLARE @EMPLEADO_INVENTARIO INT
		DECLARE @ESTADO_INVENTARIO INT
		DECLARE @FECHA_VENTA VARCHAR (30)

		SET @EMPLEADO_INVENTARIO = (SELECT ID_EMPLEADOFV FROM inserted)
		SET @ESTADO_INVENTARIO = (SELECT ID_ESTADO_FV FROM inserted)
		SET @FECHA_VENTA = (SELECT FECHA_FACV FROM inserted)
	
		INSERT INTO INVENTARIO 
		VALUES (@FECHA_VENTA,'Salida',@EMPLEADO_INVENTARIO,@ESTADO_INVENTARIO)
	END

