

GO
USE PROYECTO_APO
GO


--VALIDACIONES CARGO--

CREATE PROCEDURE V_NOMBRE_CARGO
@NOMBRE_CARGO VARCHAR (30)
AS
SELECT COUNT(*) FROM CARGO WHERE NOMBRE_CARGO = @NOMBRE_CARGO

--VALIDACION CLIENTE--

CREATE PROCEDURE V_IDENTIFICACION_CLIENTE
@IDENTIFICACION_CLIENTE INT 
AS
SELECT COUNT (*) FROM CLIENTES WHERE IDENTIFICACION_CLIENTE = @IDENTIFICACION_CLIENTE


--VALIDAR CONTRATO--
CREATE PROCEDURE V_NOMBRE_CONTRATO
@NOMBRE_CONTRATO VARCHAR (30)
AS
SELECT COUNT(*) FROM CONTRATO WHERE NOMBRE_CONTRATO = @NOMBRE_CONTRATO

--VALIDAR EMPLEADO--
CREATE PROCEDURE V_IDENTIFICACION_EMPLEADO
@IDENTIFICACION_EMPLEADO INT 
AS 
SELECT COUNT(*) FROM EMPLEADO WHERE IDENTIFICACION_EMPLEADO = @IDENTIFICACION_EMPLEADO

--VALIDAR ESTADO--
CREATE PROCEDURE V_NOMBRE_ESTADO
@NOMBRE_ESTADO VARCHAR (30)
AS
SELECT COUNT (*) FROM ESTADO WHERE NOMBRE_ESTADO = @NOMBRE_ESTADO

--VALIDAR FORMA PAGO--
CREATE PROCEDURE V_NOMBRE_FORMA_PAGO 
@NOMBRE_FORMA_PAGO VARCHAR (30)
AS
SELECT COUNT(*) FROM FORMA_PAGO WHERE NOMBRE_FORMA_PAGO = @NOMBRE_FORMA_PAGO

--VALIDAR GARANTÍA--
CREATE PROCEDURE V_TIEMPO_GARANTIA
@TIEMPO_TOTAL VARCHAR (30)
AS
SELECT COUNT (*) FROM GARANTIA WHERE TIEMPO_TOTAL = @TIEMPO_TOTAL

--VALIDAR PRODUCTOS--
CREATE PROCEDURE V_CODIGO_PRODUCTO
@CODIGO_PRODUCTO INT
AS
SELECT COUNT (*) FROM PRODUCTOS WHERE CODIGO_PRODUCTO = @CODIGO_PRODUCTO


CREATE PROCEDURE V_NOMBRE_PRODUCTO
@NOMBRE_PRODUCTO VARCHAR(30)
AS
SELECT COUNT (*) FROM PRODUCTOS WHERE NOMBRE_PRODUCTO = @NOMBRE_PRODUCTO

--VALIDAR PROVEEDORES--
CREATE PROCEDURE V_CODIGO_PROVEEDOR 
@CODIGO_PROVEEDOR INT
AS
SELECT COUNT (*) FROM PROVEEDORES WHERE CODIGO_PROVEEDOR = @CODIGO_PROVEEDOR

CREATE PROCEDURE V_NOMBRE_PROVEEDOR
@NOMBRE_PROVEEDOR VARCHAR (30)
AS
SELECT COUNT (*) FROM PROVEEDORES WHERE NOMBRE_PROVEEDOR = @NOMBRE_PROVEEDOR

--VALIDAR TPRESENTACION--
CREATE PROCEDURE V_NOMBRE_TPRESENTACION
@NOMBRE_TPRESENTACION VARCHAR (30)
AS
SELECT COUNT (*) FROM TIPO_PRESENTACION WHERE NOMBRE_TPRESENTACION = @NOMBRE_TPRESENTACION

--VALIDAR USUARIOS--
CREATE PROCEDURE V_NOMBRE_USUARIO
@NOMBRE_USUARIO VARCHAR (30)
AS
SELECT COUNT (*) FROM USUARIO WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO

CREATE PROCEDURE V_EMPLEADO_USUARIO
@ID_EMPLEADO_U INT
AS
SELECT COUNT (*) FROM EMPLEADO WHERE IDENTIFICACION_EMPLEADO = @ID_EMPLEADO_U

